# Generated by Django 3.1.14 on 2022-02-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220226_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Whether user can use the service'),
        ),
        migrations.AlterField(
            model_name='account',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Comment'),
        ),
    ]
