# Generated by Django 3.1.14 on 2022-03-01 06:48

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220301_1529'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', apps.accounts.models.CustomUserManager()),
            ],
        ),
    ]
